# Generated by Django 5.2.6 on 2026-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты (состав и кол-во)')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Фото блюда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
